name: Release
on:
  workflow_dispatch:
    inputs:
      bump:
        description: Version bump type
        required: true
        type: choice
        default: minor
        options:
          - minor
          - patch
          - major
      force:
        description: Force release (bypass blockers)
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release a new version
    steps:
    - name: Get auth token
      id: token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
      with:
        app-id: ${{ vars.SENTRY_RELEASE_BOT_CLIENT_ID }}
        private-key: ${{ secrets.SENTRY_RELEASE_BOT_PRIVATE_KEY }}
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v2
      with:
        token: ${{ steps.token.outputs.token }}
        fetch-depth: 0
        fetch-tags: true

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "20"

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Calculate version
      id: version
      run: |
        CURRENT=$(node -p "require('./package.json').version")
        NEW=$(npx semver -i ${{ inputs.bump }} $CURRENT)
        echo "current=$CURRENT" >> $GITHUB_OUTPUT
        echo "new=$NEW" >> $GITHUB_OUTPUT

    - name: Prepare release
      uses: getsentry/action-prepare-release@v1
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
      with:
        version: ${{ steps.version.outputs.new }}
        force: ${{ inputs.force }}
